import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Drops the three unmanaged `pg_trgm` GIN search indexes
 * (`add-performance-indexes`). All schema is now TypeORM-managed via entity
 * `@Index` metadata; raw expression indexes are no longer maintained. Admin
 * `ILIKE '%term%'` search boxes fall back to a sequential scan.
 *
 * Fully generated by `pnpm migration:generate` (only `import type` + kebab
 * filename applied per ADR-0001). Note: TypeORM cannot express `gin_trgm_ops`,
 * so the generated `down()` recreates plain btree indexes, not the original
 * GIN — the rollback is intentionally lossy (these indexes are being removed).
 */
export class DropTrgmIndexes1781003346988 implements MigrationInterface {
  name = 'DropTrgmIndexes1781003346988';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX "public"."IDX_mpd_title_trgm"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_users_first_name_trgm"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_users_email_trgm"`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE INDEX "IDX_users_email_trgm" ON "users" ("email") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_users_first_name_trgm" ON "users" ("first_name") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_mpd_title_trgm" ON "memory_point_details" ("title") `,
    );
  }
}
