export enum MemoryPointStatus {
  PENDING = 'PENDING',
  ADMIN_REVIEWING = 'ADMIN_REVIEWING',
  GENERATING = 'GENERATING',
  AI_REVIEWING = 'AI_REVIEWING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
